from __future__ import annotations

from pathlib import Path
import shutil

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "_site"

def copy_file(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)

def copy_tree(src: Path, dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)

if OUT.exists():
    shutil.rmtree(OUT)
OUT.mkdir(parents=True)

copy_file(ROOT / "index.html", OUT / "index.html")
copy_file(ROOT / "styles.css", OUT / "styles.css")
copy_tree(ROOT / "src", OUT / "src")
copy_file(ROOT / "data" / "catalog.json", OUT / "data" / "catalog.json")

# Runtime assets generated by npm run setup-assets.
copy_tree(ROOT / "assets" / "components", OUT / "assets" / "components")
copy_tree(ROOT / "assets" / "source", OUT / "assets" / "source")

# Keep the renderer's existing local import contract without publishing all node_modules.
three_src = ROOT / "node_modules" / "three" / "build" / "three.module.js"
if not three_src.exists():
    raise SystemExit(f"Missing Three.js module: {three_src}")
copy_file(
    three_src,
    OUT / "node_modules" / "three" / "build" / "three.module.js",
)

# Disable Jekyll processing; this is a plain static application.
(OUT / ".nojekyll").write_text("", encoding="utf-8")

required = [
    OUT / "index.html",
    OUT / "styles.css",
    OUT / "src" / "app.js",
    OUT / "src" / "renderer.js",
    OUT / "data" / "catalog.json",
    OUT / "node_modules" / "three" / "build" / "three.module.js",
]
missing = [str(path.relative_to(OUT)) for path in required if not path.exists()]
if missing:
    raise SystemExit("Pages build incomplete: " + ", ".join(missing))

print(f"Pages site prepared at {OUT}")
